export default [
  {
    "1": "!",
    "2": "@",
    "3": "#",
    "4": "$",
    "5": "%",
    "6": "^",
    "7": "&",
    "8": "*",
    "9": "(",
    "0": ")",
  },
  {
    "q": "Q",
    "w": "W",
    "e": "E",
    "r": "R",
    "t": "T",
    "y": "Y",
    "u": "U",
    "i": "I",
    "o": "O",
    "p": "P",
    "a": "A",
    "s": "S",
    "d": "D",
    "f": "F",
    "g": "G",
    "h": "H",
    "j": "J",
    "k": "K",
    "l": "L",
    "z": "Z",
    "x": "X",
    "c": "C",
    "v": "V",
    "b": "B",
    "n": "N",
    "m": "M",
  },
  {
    "`": "~",
    "-": "_",
    "=": "+",
    "[": "{",
    "]": "}",
    "\\": "|",
    ";": ":",
    "'": '"',    
    ",": "<",
    ".": ">",
    "/": "?",
  },
  {
    "caps lock": "CapsLock",
    "backspace": "Backspace",
    "tab": "Tab",
    "del": "Delete",
    "enter": "Enter",
    "shiftLeft": "ShiftLeft",
    "shiftRight": "ShiftRight",
    "ctrlLeft": "ControlLeft",
    "altLeft": "AltLeft",
    "space": "Space",
    "altRight": "AltRight",
    "ctrlRight": "ControlRight",  
  },
  
  {
    "arrowUp": null,
    "arrowLeft": null,
    "arrowDown": null,
    "arrowRight": null,
  }
];